version: '5.4'

services:
  serverstatisticscollectioncervice:
    build:
      context: .
      dockerfile: ServerStatisticsCollectionService/Dockerfile
    env_file:
      - ServerStatisticsCollectionService/.env
    